### ISSUE TITLE
Eaxmple app issue

### ISSUE THREAD

**Issue by pateelhs** [hypertrack/hypertrack-live-android#4]
E/Volley: [826] BasicNetwork.performRequest: Unexpected response code 402 for https://api.hypertrack.com/api/v1/actions/
05-16 12:30:23.831 20544-20544/**io.hypertrack.sendeta E/NetworkManagerImpl: 402: Payment needs to be enabled for using Actions. {"detail":"You have reached the action limit for your account. To continue using, please visit https://dashboard.hypertrack.com/settings"}
                                                                                 java.lang.RuntimeException: 402: Payment needs to be enabled for using Actions. {"detail":"You have reached the action limit for your account. To continue using, please visit https://dashboard.hypertrack.com/settings"}**
                                                                                     at com.hypertrack.lib.internal.common.network.NetworkErrorUtil.getException(NetworkErrorUtil.java:81)
                                                                                     at com.hypertrack.lib.internal.common.network.HTTPClient.processError(HTTPClient.java:356)
                                                                                     at com.hypertrack.lib.internal.common.network.HTTPClient.access$000(HTTPClient.java:31)
                                                                                     at com.hypertrack.lib.internal.common.network.HTTPClient$8.onErrorResponse(HTTPClient.java:134)
                                                                                     at com.android.volley.Request.deliverError(Request.java:564)
                                                                                     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by jerdog** [comment]
This issue is due to using the Production key. Switch to Test/Sandbox (and use the correct key in your forked app) mode in order to use free actions and up to 20 users for testing purposes
